### ISSUE TITLE
TODO items seem to out of date

### ISSUE THREAD

**Issue by smason** [CHV123/python-intermediate-inflammation#7]
for example, there's a TODO here

https://github.com/CHV123/python-intermediate-inflammation/blob/b3dfa791d6d03d8b7c115fb432e2877a7c8632ca/inflammation/models.py#L143

but it seems you have done the serialisation task!

**Comment by CHV123** [comment]
Fixed with latest commit

**Comment by smason** [comment]
well done, I think, that was quick  :1st_place_medal:
